### PR TITLE
Update for 1.0.0 release

### PR DESCRIPTION
**Pull request by ejpenney**

### CODE REVIEW

**Comment by cdnninja** [comment]
This looks to be a breaking change.  Looks like some lock parameters need to change.

**Comment by ejpenney** [comment]
Looks like there's already newer versions anyways.  I only have the Dual Doorbell, and while this upgrade didn't get me the functionality I wanted it _is_ working for me...

Let me know if there's anything else I can do to help, or if you want me to just close this PR.

**Comment by fuatakgun** [comment]
Thanks @ejpenney for bringing this into attention, i am testing locally with latest version and there are some breaking changes on the integration side and i need to bundle them together.

**Comment by Daneish** [comment]
> there are some breaking changes on the integration side and i need to bundle them together.

Does this mean we shouldn't update the Eufy Security Add-on to 1.1.0 before an update to the Eufy Security Integration is updated?

**Comment by fuatakgun** [comment]
Apparently, it was my bad, as long as i dont bump the schema version from integration end, updating the add-on is safe.

So, you can update the add-on now, and integration update will follow to support new devices and commands

**Comment by Daneish** [comment]
Thanks for your quick response! I have updated the add-on and can confirm everything is working. Thanks again, for all of your great work!

**Pull request closed without merging**
